### ISSUE TITLE
Reduce TASO hashtable size

### ISSUE THREAD

**Issue by lmondada** [CQCL/tket2#145]
We had a PR that did this (#133 e33fc6a8f78), but had to revert it in #144 as it was hurting optimisation performance.

Done right, it should not have any impact on optimisation.

**Comment by aborgna-q** [comment]
I'm tempted to close this as _wontfix_. Hashes are `u64`s, so even storing 10k hashes takes ~100kB.
We currently only hash circuits small enough to be inserted on the queue, so the # of circuits doesn't grow that quickly.

For example, running the barenco_tof_10 example for 100s the hash table grows to 3k2 circuits, while the peak memory consumption goes up to 390MB.
