### ISSUE TITLE
Improve python bindings modules structure

### ISSUE THREAD

**Issue by lmondada** [CQCL/tket2#169]
Couple of things that currently bug me with the bindings
- why is the package name `pyrs`
- all rust bindings are nested within `pyrs.pyrs`
- individual "classes" within `pyrs.pyrs` cannot be imported individually, i.e. one has to write

```python
from pyrs.pyrs import optimiser

optimiser.TasoOptimiser(...)
```
instead of
```python
from pyrs.pyrs.optimiser import TasoOptimiser
```

**Comment by aborgna-q** [comment]
I split this issue into #207 #208 #209, to address them separatedly.
