### ISSUE TITLE
Invalid circuit produced during TASO optimisation

### ISSUE THREAD

**Issue by aborgna-q** [CQCL/tket2#200]
The following script panics mid-optimisation. It seems an invalid circuit gets produced somewhere during the TASO run.

```python
from pytket.qasm.qasm import circuit_from_qasm
from pytket.passes import PauliSquash
from pyrs.pyrs import optimiser

def compile(circ):
    print(f"Compiling optimiser")
    opt = optimiser.TasoOptimiser.load_precompiled("nam_6_3.rwr")

    PauliSquash().apply(circ)
    return opt.optimise(circ, 30, log_progress="/tmp/progress.log")

if __name__ == "__main__":
    circ = circuit_from_qasm("failing.qasm")
    compile(circ)
```

Failing circ:

[failing.qasm.tar.gz](https://github.com/CQCL/tket2/files/13168367/failing.qasm.tar.gz)

**Comment by aborgna-q** [comment]
Update:
This circuit fails to validate after the first rewrite without the `PauliSquash` step.
```qasm
OPENQASM 2.0;
include "qelib1.inc";

qreg q[3];
cx q[2],q[0];
cx q[1],q[0];
u3(0.5*pi,0.0*pi,0.5*pi) q[2];
```

Error:
```
Edge mismatch: Extensions at source node Node(11) ([IdentList("prelude")]) exceed those at target Node(12) ([])
```

[original-circuit](https://dreampuf.github.io/GraphvizOnline/#digraph%20%7B%0A0%20%5Bshape%3Dplain%20label%3D%3C%3Ctable%20border%3D%221%22%3E%3Ctr%3E%3Ctd%20align%3D%22text%22%20border%3D%220%22%20colspan%3D%221%22%3E(0)%20DFG%3C%2Ftd%3E%3C%2Ftr%3E%3C%2Ftable%3E%3E%5D%0A1%20%5Bshape%3Dplain%20label%3D%3C%3Ctable%20border%3D%221%22%3E%3Ctr%3E%3Ctd%20align%3D%22text%22%20border%3D%220%22%20colspan%3D%223%22%3E(1)%20Input%3C%2Ftd%3E%3C%2Ftr%3E%3Ctr%3E%3Ctd%20port%3D%22out0%22%20align%3D%22text%22%20colspan%3D%221%22%20cellpadding%3D%221%22%20%3E0%3A%20qubit(%5B%5D)%3C%2Ftd%3E%3Ctd%20port%3D%22out1%22%20align%3D%22text%22%20colspan%3D%221%22%20cellpadding%3D%221%22%20%3E1%3A%20qubit(%5B%5D)%3C%2Ftd%3E%3Ctd%20port%3D%22out2%22%20align%3D%22text%22%20colspan%3D%221%22%20cellpadding%3D%221%22%20%3E2%3A%20qubit(%5B%5D)%3C%2Ftd%3E%3C%2Ftr%3E%3C%2Ftable%3E%3E%5D%0A1%3Aout0%20-%3E%203%3Ain1%20%5Bstyle%3D%22%22%5D%0A1%3Aout1%20-%3E%204%3Ain0%20%5Bstyle%3D%22%22%5D%0A1%3Aout2%20-%3E%203%3Ain0%20%5Bstyle%3D%22%22%5D%0A2%20%5Bshape%3Dplain%20label%3D%3C%3Ctable%20border%3D%221%22%3E%3Ctr%3E%3Ctd%20port%3D%22in0%22%20align%3D%22text%22%20colspan%3D%221%22%20cellpadding%3D%221%22%20%3E0%3A%20qubit(%5B%5D)%3C%2Ftd%3E%3Ctd%20port%3D%22in1%22%20align%3D%22text%22%20colspan%3D%221%22%20cellpadding%3D%221%22%20%3E1%3A%20qubit(%5B%5D)%3C%2Ftd%3E%3Ctd%20port%3D%22in2%22%20align%3D%22text%22%20colspan%3D%221%22%20cellpadding%3D%221%22%20%3E2%3A%20qubit(%5B%5D)%3C%2Ftd%3E%3C%2Ftr%3E%3Ctr%3E%3Ctd%20align%3D%22text%22%20border%3D%220%22%20colspan%3D%223%22%3E(2)%20Output%3C%2Ftd%3E%3C%2Ftr%3E%3C%2Ftable%3E%3E%5D%0A3%20%5Bshape%3Dplain%20label%3D%3C%3Ctable%20border%3D%221%22%3E%3Ctr%3E%3Ctd%20port%3D%22in0%22%20align%3D%22text%22%20colspan%3D%222%22%20cellpadding%3D%221%22%20%3E0%3A%20qubit(%5B%5D)%3C%2Ftd%3E%3Ctd%20port%3D%22in1%22%20align%3D%22text%22%20colspan%3D%222%22%20cellpadding%3D%221%22%20%3E1%3A%20qubit(%5B%5D)%3C%2Ftd%3E%3C%2Ftr%3E%3Ctr%3E%3Ctd%20align%3D%22text%22%20border%3D%220%22%20colspan%3D%224%22%3E(3)%20quantum.tket2.CX%3C%2Ftd%3E%3C%2Ftr%3E%3Ctr%3E%3Ctd%20port%3D%22out0%22%20align%3D%22text%22%20colspan%3D%222%22%20cellpadding%3D%221%22%20%3E0%3A%20qubit(%5B%5D)%3C%2Ftd%3E%3Ctd%20port%3D%22out1%22%20align%3D%22text%22%20colspan%3D%222%22%20cellpadding%3D%221%22%20%3E1%3A%20qubit(%5B%5D)%3C%2Ftd%3E%3C%2Ftr%3E%3C%2Ftable%3E%3E%5D%0A3%3Aout0%20-%3E%2011%3Ain0%20%5Bstyle%3D%22%22%5D%0A3%3Aout1%20-%3E%204%3Ain1%20%5Bstyle%3D%22%22%5D%0A4%20%5Bshape%3Dplain%20label%3D%3C%3Ctable%20border%3D%221%22%3E%3Ctr%3E%3Ctd%20port%3D%22in0%22%20align%3D%22text%22%20colspan%3D%222%22%20cellpadding%3D%221%22%20%3E0%3A%20qubit(%5B%5D)%3C%2Ftd%3E%3Ctd%20port%3D%22in1%22%20align%3D%22text%22%20colspan%3D%222%22%20cellpadding%3D%221%22%20%3E1%3A%20qubit(%5B%5D)%3C%2Ftd%3E%3C%2Ftr%3E%3Ctr%3E%3Ctd%20align%3D%22text%22%20border%3D%220%22%20colspan%3D%224%22%3E(4)%20quantum.tket2.CX%3C%2Ftd%3E%3C%2Ftr%3E%3Ctr%3E%3Ctd%20port%3D%22out0%22%20align%3D%22text%22%20colspan%3D%222%22%20cellpadding%3D%221%22%20%3E0%3A%20qubit(%5B%5D)%3C%2Ftd%3E%3Ctd%20port%3D%22out1%22%20align%3D%22text%22%20colspan%3D%222%22%20cellpadding%3D%221%22%20%3E1%3A%20qubit(%5B%5D)%3C%2Ftd%3E%3C%2Ftr%3E%3C%2Ftable%3E%3E%5D%0A4%3Aout0%20-%3E%202%3Ain1%20%5Bstyle%3D%22%22%5D%0A4%3Aout1%20-%3E%202%3Ain0%20%5Bstyle%3D%22%22%5D%0A5%20%5Bshape%3Dplain%20label%3D%3C%3Ctable%20border%3D%221%22%3E%3Ctr%3E%3Ctd%20align%3D%22text%22%20border%3D%220%22%20colspan%3D%221%22%3E(5)%20const%3Acustom%3Af64(0.5)%3C%2Ftd%3E%3C%2Ftr%3E%3Ctr%3E%3Ctd%20port%3D%22out0%22%20align%3D%22text%22%20colspan%3D%221%22%20cellpadding%3D%221%22%20%3E0%3A%20float64(%5B%5D)%3C%2Ftd%3E%3C%2Ftr%3E%3C%2Ftable%3E%3E%5D%0A5%3Aout0%20-%3E%206%3Ain0%20%5Bstyle%3D%22%22%5D%0A6%20%5Bshape%3Dplain%20label%3D%3C%3Ctable%20border%3D%221%22%3E%3Ctr%3E%3Ctd%20port%3D%22in0%22%20align%3D%22text%22%20colspan%3D%221%22%20cellpadding%3D%221%22%20%3E0%3A%20float64(%5B%5D)%3C%2Ftd%3E%3C%2Ftr%3E%3Ctr%3E%3Ctd%20align%3D%22text%22%20border%3D%220%22%20colspan%3D%221%22%3E(6)%20LoadConstant%3C%2Ftd%3E%3C%2Ftr%3E%3Ctr%3E%3Ctd%20port%3D%22out0%22%20align%3D%22text%22%20colspan%3D%221%22%20cellpadding%3D%221%22%20%3E0%3A%20float64(%5B%5D)%3C%2Ftd%3E%3C%2Ftr%3E%3C%2Ftable%3E%3E%5D%0A6%3Aout0%20-%3E%2011%3Ain1%20%5Bstyle%3D%22%22%5D%0A7%20%5Bshape%3Dplain%20label%3D%3C%3Ctable%20border%3D%221%22%3E%3Ctr%3E%3Ctd%20align%3D%22text%22%20border%3D%220%22%20colspan%3D%221%22%3E(7)%20const%3Acustom%3Af64(0)%3C%2Ftd%3E%3C%2Ftr%3E%3Ctr%3E%3Ctd%20port%3D%22out0%22%20align%3D%22text%22%20colspan%3D%221%22%20cellpadding%3D%221%22%20%3E0%3A%20float64(%5B%5D)%3C%2Ftd%3E%3C%2Ftr%3E%3C%2Ftable%3E%3E%5D%0A7%3Aout0%20-%3E%208%3Ain0%20%5Bstyle%3D%22%22%5D%0A8%20%5Bshape%3Dplain%20label%3D%3C%3Ctable%20border%3D%221%22%3E%3Ctr%3E%3Ctd%20port%3D%22in0%22%20align%3D%22text%22%20colspan%3D%221%22%20cellpadding%3D%221%22%20%3E0%3A%20float64(%5B%5D)%3C%2Ftd%3E%3C%2Ftr%3E%3Ctr%3E%3Ctd%20align%3D%22text%22%20border%3D%220%22%20colspan%3D%221%22%3E(8)%20LoadConstant%3C%2Ftd%3E%3C%2Ftr%3E%3Ctr%3E%3Ctd%20port%3D%22out0%22%20align%3D%22text%22%20colspan%3D%221%22%20cellpadding%3D%221%22%20%3E0%3A%20float64(%5B%5D)%3C%2Ftd%3E%3C%2Ftr%3E%3C%2Ftable%3E%3E%5D%0A8%3Aout0%20-%3E%2011%3Ain2%20%5Bstyle%3D%22%22%5D%0A9%20%5Bshape%3Dplain%20label%3D%3C%3Ctable%20border%3D%221%22%3E%3Ctr%3E%3Ctd%20align%3D%22text%22%20border%3D%220%22%20colspan%3D%221%22%3E(9)%20const%3Acustom%3Af64(0.5)%3C%2Ftd%3E%3C%2Ftr%3E%3Ctr%3E%3Ctd%20port%3D%22out0%22%20align%3D%22text%22%20colspan%3D%221%22%20cellpadding%3D%221%22%20%3E0%3A%20float64(%5B%5D)%3C%2Ftd%3E%3C%2Ftr%3E%3C%2Ftable%3E%3E%5D%0A9%3Aout0%20-%3E%2010%3Ain0%20%5Bstyle%3D%22%22%5D%0A10%20%5Bshape%3Dplain%20label%3D%3C%3Ctable%20border%3D%221%22%3E%3Ctr%3E%3Ctd%20port%3D%22in0%22%20align%3D%22text%22%20colspan%3D%221%22%20cellpadding%3D%221%22%20%3E0%3A%20float64(%5B%5D)%3C%2Ftd%3E%3C%2Ftr%3E%3Ctr%3E%3Ctd%20align%3D%22text%22%20border%3D%220%22%20colspan%3D%221%22%3E(10)%20LoadConstant%3C%2Ftd%3E%3C%2Ftr%3E%3Ctr%3E%3Ctd%20port%3D%22out0%22%20align%3D%22text%22%20colspan%3D%221%22%20cellpadding%3D%221%22%20%3E0%3A%20float64(%5B%5D)%3C%2Ftd%3E%3C%2Ftr%3E%3C%2Ftable%3E%3E%5D%0A10%3Aout0%20-%3E%2011%3Ain3%20%5Bstyle%3D%22%22%5D%0A11%20%5Bshape%3Dplain%20label%3D%3C%3Ctable%20border%3D%221%22%3E%3Ctr%3E%3Ctd%20port%3D%22in0%22%20align%3D%22text%22%20colspan%3D%221%22%20cellpadding%3D%221%22%20%3E0%3A%20qubit(%5B%5D)%3C%2Ftd%3E%3Ctd%20port%3D%22in1%22%20align%3D%22text%22%20colspan%3D%221%22%20cellpadding%3D%221%22%20%3E1%3A%20float64(%5B%5D)%3C%2Ftd%3E%3Ctd%20port%3D%22in2%22%20align%3D%22text%22%20colspan%3D%221%22%20cellpadding%3D%221%22%20%3E2%3A%20float64(%5B%5D)%3C%2Ftd%3E%3Ctd%20port%3D%22in3%22%20align%3D%22text%22%20colspan%3D%221%22%20cellpadding%3D%221%22%20%3E3%3A%20float64(%5B%5D)%3C%2Ftd%3E%3C%2Ftr%3E%3Ctr%3E%3Ctd%20align%3D%22text%22%20border%3D%220%22%20colspan%3D%224%22%3E(11)%20TKET1.TKET1%20Json%20Op%3C%2Ftd%3E%3C%2Ftr%3E%3Ctr%3E%3Ctd%20port%3D%22out0%22%20align%3D%22text%22%20colspan%3D%224%22%20cellpadding%3D%221%22%20%3E0%3A%20qubit(%5B%5D)%3C%2Ftd%3E%3C%2Ftr%3E%3C%2Ftable%3E%3E%5D%0A11%3Aout0%20-%3E%202%3Ain2%20%5Bstyle%3D%22%22%5D%0A%7D)

[post-rewrite circuit](https://dreampuf.github.io/GraphvizOnline/#digraph%20%7B%0A0%20%5Bshape%3Dplain%20label%3D%3C%3Ctable%20border%3D%221%22%3E%3Ctr%3E%3Ctd%20align%3D%22text%22%20border%3D%220%22%20colspan%3D%221%22%3E(0)%20DFG%3C%2Ftd%3E%3C%2Ftr%3E%3C%2Ftable%3E%3E%5D%0A1%20%5Bshape%3Dplain%20label%3D%3C%3Ctable%20border%3D%221%22%3E%3Ctr%3E%3Ctd%20align%3D%22text%22%20border%3D%220%22%20colspan%3D%223%22%3E(1)%20Input%3C%2Ftd%3E%3C%2Ftr%3E%3Ctr%3E%3Ctd%20port%3D%22out0%22%20align%3D%22text%22%20colspan%3D%221%22%20cellpadding%3D%221%22%20%3E0%3A%20qubit(%5B%5D)%3C%2Ftd%3E%3Ctd%20port%3D%22out1%22%20align%3D%22text%22%20colspan%3D%221%22%20cellpadding%3D%221%22%20%3E1%3A%20qubit(%5B%5D)%3C%2Ftd%3E%3Ctd%20port%3D%22out2%22%20align%3D%22text%22%20colspan%3D%221%22%20cellpadding%3D%221%22%20%3E2%3A%20qubit(%5B%5D)%3C%2Ftd%3E%3C%2Ftr%3E%3C%2Ftable%3E%3E%5D%0A1%3Aout0%20-%3E%2012%3Ain1%20%5Bstyle%3D%22%22%5D%0A1%3Aout1%20-%3E%2012%3Ain0%20%5Bstyle%3D%22%22%5D%0A1%3Aout2%20-%3E%2013%3Ain0%20%5Bstyle%3D%22%22%5D%0A2%20%5Bshape%3Dplain%20label%3D%3C%3Ctable%20border%3D%221%22%3E%3Ctr%3E%3Ctd%20port%3D%22in0%22%20align%3D%22text%22%20colspan%3D%221%22%20cellpadding%3D%221%22%20%3E0%3A%20qubit(%5B%5D)%3C%2Ftd%3E%3Ctd%20port%3D%22in1%22%20align%3D%22text%22%20colspan%3D%221%22%20cellpadding%3D%221%22%20%3E1%3A%20qubit(%5B%5D)%3C%2Ftd%3E%3Ctd%20port%3D%22in2%22%20align%3D%22text%22%20colspan%3D%221%22%20cellpadding%3D%221%22%20%3E2%3A%20qubit(%5B%5D)%3C%2Ftd%3E%3C%2Ftr%3E%3Ctr%3E%3Ctd%20align%3D%22text%22%20border%3D%220%22%20colspan%3D%223%22%3E(2)%20Output%3C%2Ftd%3E%3C%2Ftr%3E%3C%2Ftable%3E%3E%5D%0A5%20%5Bshape%3Dplain%20label%3D%3C%3Ctable%20border%3D%221%22%3E%3Ctr%3E%3Ctd%20align%3D%22text%22%20border%3D%220%22%20colspan%3D%221%22%3E(5)%20const%3Acustom%3Af64(0.5)%3C%2Ftd%3E%3C%2Ftr%3E%3Ctr%3E%3Ctd%20port%3D%22out0%22%20align%3D%22text%22%20colspan%3D%221%22%20cellpadding%3D%221%22%20%3E0%3A%20float64(%5B%5D)%3C%2Ftd%3E%3C%2Ftr%3E%3C%2Ftable%3E%3E%5D%0A5%3Aout0%20-%3E%206%3Ain0%20%5Bstyle%3D%22%22%5D%0A6%20%5Bshape%3Dplain%20label%3D%3C%3Ctable%20border%3D%221%22%3E%3Ctr%3E%3Ctd%20port%3D%22in0%22%20align%3D%22text%22%20colspan%3D%221%22%20cellpadding%3D%221%22%20%3E0%3A%20float64(%5B%5D)%3C%2Ftd%3E%3C%2Ftr%3E%3Ctr%3E%3Ctd%20align%3D%22text%22%20border%3D%220%22%20colspan%3D%221%22%3E(6)%20LoadConstant%3C%2Ftd%3E%3C%2Ftr%3E%3Ctr%3E%3Ctd%20port%3D%22out0%22%20align%3D%22text%22%20colspan%3D%221%22%20cellpadding%3D%221%22%20%3E0%3A%20float64(%5B%5D)%3C%2Ftd%3E%3C%2Ftr%3E%3C%2Ftable%3E%3E%5D%0A6%3Aout0%20-%3E%2011%3Ain1%20%5Bstyle%3D%22%22%5D%0A7%20%5Bshape%3Dplain%20label%3D%3C%3Ctable%20border%3D%221%22%3E%3Ctr%3E%3Ctd%20align%3D%22text%22%20border%3D%220%22%20colspan%3D%221%22%3E(7)%20const%3Acustom%3Af64(0)%3C%2Ftd%3E%3C%2Ftr%3E%3Ctr%3E%3Ctd%20port%3D%22out0%22%20align%3D%22text%22%20colspan%3D%221%22%20cellpadding%3D%221%22%20%3E0%3A%20float64(%5B%5D)%3C%2Ftd%3E%3C%2Ftr%3E%3C%2Ftable%3E%3E%5D%0A7%3Aout0%20-%3E%208%3Ain0%20%5Bstyle%3D%22%22%5D%0A8%20%5Bshape%3Dplain%20label%3D%3C%3Ctable%20border%3D%221%22%3E%3Ctr%3E%3Ctd%20port%3D%22in0%22%20align%3D%22text%22%20colspan%3D%221%22%20cellpadding%3D%221%22%20%3E0%3A%20float64(%5B%5D)%3C%2Ftd%3E%3C%2Ftr%3E%3Ctr%3E%3Ctd%20align%3D%22text%22%20border%3D%220%22%20colspan%3D%221%22%3E(8)%20LoadConstant%3C%2Ftd%3E%3C%2Ftr%3E%3Ctr%3E%3Ctd%20port%3D%22out0%22%20align%3D%22text%22%20colspan%3D%221%22%20cellpadding%3D%221%22%20%3E0%3A%20float64(%5B%5D)%3C%2Ftd%3E%3C%2Ftr%3E%3C%2Ftable%3E%3E%5D%0A8%3Aout0%20-%3E%2011%3Ain2%20%5Bstyle%3D%22%22%5D%0A9%20%5Bshape%3Dplain%20label%3D%3C%3Ctable%20border%3D%221%22%3E%3Ctr%3E%3Ctd%20align%3D%22text%22%20border%3D%220%22%20colspan%3D%221%22%3E(9)%20const%3Acustom%3Af64(0.5)%3C%2Ftd%3E%3C%2Ftr%3E%3Ctr%3E%3Ctd%20port%3D%22out0%22%20align%3D%22text%22%20colspan%3D%221%22%20cellpadding%3D%221%22%20%3E0%3A%20float64(%5B%5D)%3C%2Ftd%3E%3C%2Ftr%3E%3C%2Ftable%3E%3E%5D%0A9%3Aout0%20-%3E%2010%3Ain0%20%5Bstyle%3D%22%22%5D%0A10%20%5Bshape%3Dplain%20label%3D%3C%3Ctable%20border%3D%221%22%3E%3Ctr%3E%3Ctd%20port%3D%22in0%22%20align%3D%22text%22%20colspan%3D%221%22%20cellpadding%3D%221%22%20%3E0%3A%20float64(%5B%5D)%3C%2Ftd%3E%3C%2Ftr%3E%3Ctr%3E%3Ctd%20align%3D%22text%22%20border%3D%220%22%20colspan%3D%221%22%3E(10)%20LoadConstant%3C%2Ftd%3E%3C%2Ftr%3E%3Ctr%3E%3Ctd%20port%3D%22out0%22%20align%3D%22text%22%20colspan%3D%221%22%20cellpadding%3D%221%22%20%3E0%3A%20float64(%5B%5D)%3C%2Ftd%3E%3C%2Ftr%3E%3C%2Ftable%3E%3E%5D%0A10%3Aout0%20-%3E%2011%3Ain3%20%5Bstyle%3D%22%22%5D%0A11%20%5Bshape%3Dplain%20label%3D%3C%3Ctable%20border%3D%221%22%3E%3Ctr%3E%3Ctd%20port%3D%22in0%22%20align%3D%22text%22%20colspan%3D%221%22%20cellpadding%3D%221%22%20%3E0%3A%20qubit(%5B%5D)%3C%2Ftd%3E%3Ctd%20port%3D%22in1%22%20align%3D%22text%22%20colspan%3D%221%22%20cellpadding%3D%221%22%20%3E1%3A%20float64(%5B%5D)%3C%2Ftd%3E%3Ctd%20port%3D%22in2%22%20align%3D%22text%22%20colspan%3D%221%22%20cellpadding%3D%221%22%20%3E2%3A%20float64(%5B%5D)%3C%2Ftd%3E%3Ctd%20port%3D%22in3%22%20align%3D%22text%22%20colspan%3D%221%22%20cellpadding%3D%221%22%20%3E3%3A%20float64(%5B%5D)%3C%2Ftd%3E%3C%2Ftr%3E%3Ctr%3E%3Ctd%20align%3D%22text%22%20border%3D%220%22%20colspan%3D%224%22%3E(11)%20TKET1.TKET1%20Json%20Op%3C%2Ftd%3E%3C%2Ftr%3E%3Ctr%3E%3Ctd%20port%3D%22out0%22%20align%3D%22text%22%20colspan%3D%224%22%20cellpadding%3D%221%22%20%3E0%3A%20qubit(%5B%5D)%3C%2Ftd%3E%3C%2Ftr%3E%3C%2Ftable%3E%3E%5D%0A11%3Aout0%20-%3E%202%3Ain2%20%5Bstyle%3D%22%22%5D%0A12%20%5Bshape%3Dplain%20label%3D%3C%3Ctable%20border%3D%221%22%3E%3Ctr%3E%3Ctd%20port%3D%22in0%22%20align%3D%22text%22%20colspan%3D%222%22%20cellpadding%3D%221%22%20%3E0%3A%20qubit(%5B%5D)%3C%2Ftd%3E%3Ctd%20port%3D%22in1%22%20align%3D%22text%22%20colspan%3D%222%22%20cellpadding%3D%221%22%20%3E1%3A%20qubit(%5B%5D)%3C%2Ftd%3E%3C%2Ftr%3E%3Ctr%3E%3Ctd%20align%3D%22text%22%20border%3D%220%22%20colspan%3D%224%22%3E(12)%20quantum.tket2.CX%3C%2Ftd%3E%3C%2Ftr%3E%3Ctr%3E%3Ctd%20port%3D%22out0%22%20align%3D%22text%22%20colspan%3D%222%22%20cellpadding%3D%221%22%20%3E0%3A%20qubit(%5B%5D)%3C%2Ftd%3E%3Ctd%20port%3D%22out1%22%20align%3D%22text%22%20colspan%3D%222%22%20cellpadding%3D%221%22%20%3E1%3A%20qubit(%5B%5D)%3C%2Ftd%3E%3C%2Ftr%3E%3C%2Ftable%3E%3E%5D%0A12%3Aout0%20-%3E%202%3Ain1%20%5Bstyle%3D%22%22%5D%0A12%3Aout1%20-%3E%2013%3Ain1%20%5Bstyle%3D%22%22%5D%0A13%20%5Bshape%3Dplain%20label%3D%3C%3Ctable%20border%3D%221%22%3E%3Ctr%3E%3Ctd%20port%3D%22in0%22%20align%3D%22text%22%20colspan%3D%222%22%20cellpadding%3D%221%22%20%3E0%3A%20qubit(%5B%5D)%3C%2Ftd%3E%3Ctd%20port%3D%22in1%22%20align%3D%22text%22%20colspan%3D%222%22%20cellpadding%3D%221%22%20%3E1%3A%20qubit(%5B%5D)%3C%2Ftd%3E%3C%2Ftr%3E%3Ctr%3E%3Ctd%20align%3D%22text%22%20border%3D%220%22%20colspan%3D%224%22%3E(13)%20quantum.tket2.CX%3C%2Ftd%3E%3C%2Ftr%3E%3Ctr%3E%3Ctd%20port%3D%22out0%22%20align%3D%22text%22%20colspan%3D%222%22%20cellpadding%3D%221%22%20%3E0%3A%20qubit(%5B%5D)%3C%2Ftd%3E%3Ctd%20port%3D%22out1%22%20align%3D%22text%22%20colspan%3D%222%22%20cellpadding%3D%221%22%20%3E1%3A%20qubit(%5B%5D)%3C%2Ftd%3E%3C%2Ftr%3E%3C%2Ftable%3E%3E%5D%0A13%3Aout0%20-%3E%2011%3Ain0%20%5Bstyle%3D%22%22%5D%0A13%3Aout1%20-%3E%202%3Ain0%20%5Bstyle%3D%22%22%5D%0A%7D%0A)

**Comment by aborgna-q** [comment]
Repreducible case in here: https://github.com/CQCL/tket2/blob/debug/validation-fail-example/examples/failing_validation.rs

Checkout the `debug/validation-fail-example` branch and run
```cargo run --example failing_validation```

**Comment by croyzor** [comment]
The test case seems to be working now after recent changes to extension inference! I rebased on the current head of tket2 (d8a7bd54) and running the example gives no such error! I've pushed the rebase to the `debug/validation-fail-example` branch

**Comment by aborgna-q** [comment]
Seems to be fixed :+1: 
(It'd be nice to know how :P )
