### ISSUE TITLE
Rename TASO -> Badger

### ISSUE THREAD

**Issue by lmondada** [CQCL/tket2#224]
I am finally taking the time to read the original "TASO" paper.

https://dl.acm.org/doi/10.1145/3341301.3359630

Turns out TASO stands for "Tensor Algebra SuperOptimiser" and doesn't refer to the optimiser, but the whole idea of generating rewrite rules automatically, in the context of NN computational graphs... The optimiser itself is refered to as a "cost-based backtracking search", which is a pretty descriptive term that we could add to the documentation.

So it's probably a good idea to get rid of the TASO name. I'd like to suggest the more fun name of "badger" optimiser. Coz in Italian "tasso" means a badger.

**Comment by aborgna-q** [comment]
:badger:
