### ISSUE TITLE
Add a python-defined layer over the bindings.

### ISSUE THREAD

**Issue by aborgna-q** [CQCL/tket2#350]
Move the bindings to a `tket2._tket2` submodule and re-define all structures from python, backed by their binded counterparts.

See [Quantomatic/quizx](https://github.com/Quantomatic/quizx/tree/master/pybindings) for an example.

This gives us more flexibility on the python interface, where we can define methods that better reflect the python conventions.
Additionally, typing information is simpler and less error-prone; we only need the hand-written .pyi for the reduced binded methods and missing values will not affect the external API.

**Comment by ss2165** [comment]
Summary of in-person discussion:
Following on from #465, we intend to use hugr-py `Node, Port, Wire` types in the surface python layer. For ops and types, things like `HugrType` or `TK2Ops` should implement the hugr-py `Op` and `Type` protocols for compatibility. They should also compare as equal to their hugr-py counterparts.

**Comment by aborgna-q** [comment]
Closing this, as it will be included in any new tket2 bindings support / replaced by hugr-py uses.
