### ISSUE TITLE
Lower quantum ops in tket2-hseries

### ISSUE THREAD

**Issue by doug-q** [CQCL/tket2#490]
Lower all Tk2Ops to HSeriesOps

**Comment by ss2165** [comment]
Eldarion and downwards expect quantum operations to be in H-series gateset (phasedX, ZZMax, ZZPhase, Rz, TK2). Currently you can program in guppy in this set and everything works. Users will want to use more familiar gates, so ideally we should allow them to program using all the standard gates from TKET1 and use tket1 rebasing. We can break this down in to two somewhat parallel tasks:

- [ ] In tket2-hseries rebase tket2 quantum operations by calling out to pytket
    - Find flat regions (for guppy, almost always basic blocks)
    - Attempt to convert region to tket1 (if quantum operations in region and conversion fails, report error)
    - Call out to pytket using py03 (requires python in environment with pytket installed, but assuming a tket2-py install this should be the case) and rebase to hseries.
    - Attempt to convert back to HUGR.
    - Replace region with a rewrite.
- [ ] Add tket1 ops extension. Ideally: script for generating a (serialized) extension from `pytket.OpType`.
    - Attach lowering HUGRs for matching tket2 quantum operations (and vice versa).
    - Support all TKET1 extension operations in TKET1<->HUGR conversion code.
