### ISSUE TITLE
Conflicting definitions of angle type

### ISSUE THREAD

**Issue by doug-q** [CQCL/tket2#606]
`ANGLE_TYPE` has a comment describing the type as a dyadic rational multiple of \pi.

Other comments describe it as a dyadic rational multiple of 2\pi.

In my opinion the 2\pi definition is better because it allows the invariant that the numerator is always less than the denominator

**Comment by cqc-alec** [comment]
The two definitions are equivalent, but are perhaps both missing the clarifying point that angles that are equivalent mod 2π are considered equal.

(This means that the numerator isn't uniquely determined by the angle, so the problem goes away. We can still define a "canonical" numerator/denominator though which I agree should be the multiplier of 2π.)

**Comment by cqc-alec** [comment]
Yeah I just meant they are semantically equivalent, because x is a dyadic rational multiple of 2π if and only if x is a dyadic rational multiple of π.
